# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tristan Brindle
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  (c) Tristan Brindle.
  Code samples are MIT licensed unless otherwise stated.
  Attribution is appreciated.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tcbrindle.github.io" # the base hostname & protocol for your site
twitter_username: tristanbrindle
github_username:  tcbrindle

# Build settings
#markdown: kramdown
markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions: ["no_intra_emphasis", "smart", "autolink", "tables", "with_toc_data"]
